Match User voxbridge
    AuthorizedKeysFile /etc/ssh/voxbridge.keys
    AuthorizedKeysCommand none
    PasswordAuthentication no
    AuthenticationMethods publickey
    AllowTcpForwarding local
    PermitOpen 127.0.0.1:8080
    AllowStreamLocalForwarding no
    AllowAgentForwarding no
    X11Forwarding no
    PermitTTY no
    PermitUserRC no
    MaxSessions 0
    ForceCommand /bin/false
Match all
