"""The Vox Studio agent crew.

The crew takes an editorial Brief and drives the Agent production interface to a narrated
preview: discover the contracts, author a VideoPlan, repair it against the compiler's
refusals, Preflight, record a Take, compile, render — or Decline, when the catalog cannot
serve what the Brief asks for.

It works from inside an isolated work root that begins as the launcher and the Brief's request
and nothing else, and it never sees repository source. Everything it knows about production it
asked for.
"""

from .census import (
    AnchorCount,
    AnchorTally,
    CensusIncomplete,
    Part,
    PrefixCensus,
    Repeat,
    Unparsed,
    take_census,
)
from .census_record import render_prefix_census
from .client import (
    Artifact,
    ArtifactCorrupted,
    ArtifactMissing,
    ArtifactOutsideRun,
    ProductionClient,
    ProductionClientError,
    ProductionUnavailable,
    UnknownRun,
)
from .context import (
    CHARS_PER_TOKEN,
    FRESH_CHARS,
    FRESH_CHARS_PER_ASK,
    RESIDENT_CHARS,
    RESIDENT_CHARS_ALLOWED,
    Ask,
    ContextBudget,
    ContextBudgetExceeded,
    ContextSpend,
    context_budget,
    tokens,
)
from .converge import (
    BUDGET_EXHAUSTED,
    DISPATCHED,
    MARGIN_CLEAR,
    PAUSED,
    RENDERED,
    REUSED,
    STOPPED,
    BriefUnnamed,
    ConvergedRun,
    RecordingQuota,
    RepairBudget,
    beat_shape,
    converge,
    preflight_risks,
    quota_read,
    repair_budget,
    spend_of,
    take_preserved,
    target_seconds,
)
from .envelopes import (
    ArtifactDescriptor,
    EnvelopeError,
    MalformedEnvelope,
    NextCommand,
    ResultEnvelope,
    RunHandle,
    parse_envelope,
)
from .evidence import (
    ARTIFACTS,
    ASSERTIONS,
    COMMANDS,
    ENVIRONMENT,
    FAIL,
    HASH_INDEX,
    NOT_EVIDENCED,
    PASS,
    SUMMARY,
    TRANSCRIPT,
    BundleInvalid,
    EvidenceBundle,
    EvidenceLeaked,
    assemble,
    machine_verdict,
    read_bundle,
    verify,
    write_bundle,
)
from .http_client import HttpProductionClient
from .local_client import LocalProductionClient
from .planner import (
    AdkPlanAuthor,
    AuthoredPlan,
    AuthoredRun,
    CachedPrefix,
    Finding,
    HandedPlanAuthor,
    InstructionsLeaked,
    LeakScan,
    PlanAuthor,
    PlanNotAuthored,
    PlanNotRepairable,
    PublishedForm,
    anchor_forms,
    author_plan,
    authoring_ask,
    cache_prefix,
    category_part,
    instructions,
    message_text,
    plan_and_produce,
    repair_ask,
    repair_plan,
    review,
    scan_for_leaks,
)
from .producer import READ_BACK, ProducedRun, produce, read_back_artifacts
from .refusals import Refusal, read_refusal
from .teaching_surface import DiscoveryRefused, TeachingSurface, read_teaching_surface

__all__ = [
    "ARTIFACTS",
    "ASSERTIONS",
    "AdkPlanAuthor",
    "AnchorCount",
    "AnchorTally",
    "Artifact",
    "ArtifactCorrupted",
    "ArtifactDescriptor",
    "ArtifactMissing",
    "ArtifactOutsideRun",
    "Ask",
    "AuthoredPlan",
    "AuthoredRun",
    "BUDGET_EXHAUSTED",
    "BriefUnnamed",
    "BundleInvalid",
    "CHARS_PER_TOKEN",
    "COMMANDS",
    "CachedPrefix",
    "CensusIncomplete",
    "ContextBudget",
    "ContextBudgetExceeded",
    "ContextSpend",
    "ConvergedRun",
    "DISPATCHED",
    "DiscoveryRefused",
    "ENVIRONMENT",
    "EnvelopeError",
    "EvidenceBundle",
    "EvidenceLeaked",
    "FAIL",
    "FRESH_CHARS",
    "FRESH_CHARS_PER_ASK",
    "Finding",
    "HASH_INDEX",
    "HandedPlanAuthor",
    "HttpProductionClient",
    "InstructionsLeaked",
    "LeakScan",
    "LocalProductionClient",
    "MARGIN_CLEAR",
    "MalformedEnvelope",
    "NOT_EVIDENCED",
    "NextCommand",
    "PASS",
    "PAUSED",
    "Part",
    "PlanAuthor",
    "PlanNotAuthored",
    "PlanNotRepairable",
    "PrefixCensus",
    "ProducedRun",
    "ProductionClient",
    "ProductionClientError",
    "ProductionUnavailable",
    "PublishedForm",
    "READ_BACK",
    "RENDERED",
    "RESIDENT_CHARS",
    "RESIDENT_CHARS_ALLOWED",
    "REUSED",
    "RecordingQuota",
    "Refusal",
    "RepairBudget",
    "Repeat",
    "ResultEnvelope",
    "RunHandle",
    "STOPPED",
    "SUMMARY",
    "TRANSCRIPT",
    "TeachingSurface",
    "UnknownRun",
    "Unparsed",
    "anchor_forms",
    "assemble",
    "author_plan",
    "authoring_ask",
    "beat_shape",
    "cache_prefix",
    "category_part",
    "context_budget",
    "converge",
    "instructions",
    "machine_verdict",
    "message_text",
    "parse_envelope",
    "plan_and_produce",
    "preflight_risks",
    "produce",
    "quota_read",
    "read_back_artifacts",
    "read_bundle",
    "read_refusal",
    "read_teaching_surface",
    "render_prefix_census",
    "repair_ask",
    "repair_budget",
    "repair_plan",
    "review",
    "scan_for_leaks",
    "spend_of",
    "take_census",
    "take_preserved",
    "target_seconds",
    "tokens",
    "verify",
    "write_bundle",
]
