#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

# Ticket 03's wizard provisions; this one deploys, and they are two scripts on purpose.
# `provision-cloud-project.sh` stage 1 says gcloud is its only prerequisite, and that sentence stops
# being true the moment a 2 GB image push is bolted onto it. Provisioning also happens once and a
# deploy happens every release, so re-running thirteen provisioning stages to replace an image is
# the wrong shape. What crosses the seam is a check rather than a hope: stage 2 refuses to continue
# unless the secret the provisioner creates is already there.
#
# **The order is the design.** Secret, then image, then the env file on the box, then metadata, then
# boot. `cloud-init.yaml`'s unit is `Restart=always` with `RestartSec=10`, and it needs both the
# image and `/etc/vox/service.env`. Applying the metadata before either exists gives a unit that
# crash-loops every ten seconds on a machine reachable only through an IAP tunnel. Every stage here
# that could leave the box in that state verifies its predecessor first, and says so.

ENV_FILE="${VOX_CLOUD_ENV_FILE:-$HOME/.vox-cloud.env}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REGION="europe-west1"
REPO="vox"
IMAGE_NAME="production"
LOCAL_IMAGE="vox-production:latest"
INSTANCE="vox-service"
CLOUD_INIT="$REPO_ROOT/deploy/cloud-init.yaml"
DOCKERIGNORE="$REPO_ROOT/.dockerignore"
SERVICE_ENV="/etc/vox/service.env"
# Google's documented ceiling for one metadata value. The rendered unit file is a few kilobytes, so
# this is a guard against a future edit rather than a live worry — but a metadata write that is
# rejected for size after the image is already pushed is a bad place to learn the number.
METADATA_MAX_BYTES=262144

# The five the container reads at start. Named here rather than imported so this wizard can say
# which ones it checked, and so a drift between the two lists is visible in a diff.
PRODUCTION_SECRETS=(ELEVENLABS_API_KEY VOX_GRANT_KEY VOX_RUN_HMAC_KEY VOX_RUN_KEY_ID VOX_NETWORK_TOKEN)

# ── gcloud and docker, resolved once ──────────────────────────────────────
# Identical to the provisioner's resolver, and deliberately duplicated rather than sourced: a
# deploy wizard that cannot run without the provisioning wizard present is a coupling nobody asked
# for, and this is twenty lines.
GCLOUD=""
resolve_gcloud() {
  local candidate
  for candidate in gcloud gcloud.cmd; do
    if command -v "$candidate" >/dev/null 2>&1; then GCLOUD="$candidate"; return 0; fi
  done
  for candidate in \
    "$HOME/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud" \
    "$HOME/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd" \
    "/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin/gcloud" \
    "/c/Program Files (x86)/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd" \
    "$HOME/google-cloud-sdk/bin/gcloud"; do
    if [[ -f "$candidate" ]]; then GCLOUD="$candidate"; return 0; fi
  done
  return 1
}
gc() { "$GCLOUD" "$@"; }

DOCKER=""
resolve_docker() {
  local candidate
  for candidate in docker docker.exe; do
    if command -v "$candidate" >/dev/null 2>&1; then DOCKER="$candidate"; return 0; fi
  done
  return 1
}
# Every docker invocation here passes image references and no filesystem paths, which matters on
# Windows: Git Bash's MSYS layer rewrites arguments that look like absolute POSIX paths, and that is
# what breaks `docker run --volume /app/...` under Git Bash. An image reference does not start with
# a slash, so nothing here is rewritten. Keep it that way — if a path argument is ever needed,
# prefix the call with MSYS_NO_PATHCONV=1 rather than discovering it in a half-finished deploy.
dk() { "$DOCKER" "$@"; }

# ── the box, over the tunnel ──────────────────────────────────────────────
# `gc compute ssh "$INSTANCE" --zone="$ZONE" --tunnel-through-iap --command=…` appeared six times
# with the same four arguments hand-written each time. There are two shapes and they are different
# enough to be two functions rather than one with a flag:
#
#   on_box_line   read one value back. Strips the CR that Git Bash leaves on every line, keeps the
#                 last line so a login banner cannot be mistaken for the answer, and never fails —
#                 the caller decides what an empty answer means, because "the tunnel did not
#                 answer" and "the file is not there" are different faults and callers here treat
#                 them differently.
#   on_box        run it and let the operator see the output, passing the exit status through.
#
# Neither hides the tunnel: a caller that needs a flag these do not pass should write the call out
# in full rather than grow a third parameter here.
on_box_line() {
  gc compute ssh "$INSTANCE" --zone="$ZONE" --tunnel-through-iap --command="$1" 2>/dev/null \
    | tr -d '\r' | tail -n1 || true
}
on_box() {
  gc compute ssh "$INSTANCE" --zone="$ZONE" --tunnel-through-iap --command="$1"
}

VERIFY_FAILURES=0
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; VERIFY_FAILURES=$((VERIFY_FAILURES + 1)); }

# halt "why" stops the wizard where continuing would leave the VM crash-looping. Every use marks a
# precondition the *next* stage would silently depend on.
halt() {
  printf '\n'
  bad "$1"
  note "Nothing has been changed by this stage. Fix the above and re-run; this wizard is idempotent."
  printf '\n'
  exit 1
}

banner "Vox production service — deploying the container"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Both tools are here, and the project is the one you provisioned"
if resolve_gcloud; then ok "found $GCLOUD"; else halt "gcloud is not on this machine — run scripts/provision-cloud-project.sh first"; fi
if resolve_docker; then
  ok "found $DOCKER"
else
  say "Docker is this wizard's second prerequisite, and the reason it is not part of the"
  say "provisioning wizard: that one needs gcloud and nothing else."
  halt "docker is not on this machine — install Docker Desktop, then re-run"
fi
if ! dk info >/dev/null 2>&1; then
  halt "docker is installed but its daemon is not running — start Docker Desktop, then re-run"
fi
ok "the docker daemon is up"

# The provisioner writes these. Reading them rather than asking again means the two wizards cannot
# disagree about which project is being deployed to, which is the kind of mistake that is only
# discovered afterwards.
if [[ ! -f "$ENV_FILE" ]]; then
  halt "$ENV_FILE does not exist — run scripts/provision-cloud-project.sh first"
fi
set -a
# shellcheck source=/dev/null  # the path is chosen at runtime; there is nothing constant to follow
. "$ENV_FILE"
set +a
for key in VOX_CLOUD_PROJECT VOX_CLOUD_ZONE VOX_PRODUCTION_SA; do
  if [[ -z "${!key:-}" ]]; then halt "$key is not in $ENV_FILE — re-run the provisioning wizard"; fi
done
ZONE="$VOX_CLOUD_ZONE"
ok "project $VOX_CLOUD_PROJECT, zone $ZONE, from $ENV_FILE"
note "The zone is read, never assumed: the provisioner tries the region's zones in turn and"
note "records whichever one supplied the disk, so it is not necessarily ${REGION}-b."
gc config set project "$VOX_CLOUD_PROJECT" >/dev/null 2>&1 || true

IMAGE_PATH="${REGION}-docker.pkg.dev/${VOX_CLOUD_PROJECT}/${REPO}/${IMAGE_NAME}"

if ! gc compute instances describe "$INSTANCE" --zone="$ZONE" >/dev/null 2>&1; then
  halt "instance $INSTANCE does not exist in $ZONE — the provisioning wizard has not finished"
fi
ok "instance $INSTANCE exists in $ZONE"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The transport's signing key exists, and production alone can read it"
say "This stage creates nothing. Creating a credential belongs to the provisioning wizard,"
say "and a deploy script that can mint one is a deploy script that can mint the wrong one."
say ""
say "It is first because the unit reads every one of these at container start. A missing"
say "secret is not a startup warning — it is a crash loop behind a tunnel."

MISSING_SECRETS=()
for name in "${PRODUCTION_SECRETS[@]}"; do
  if gc secrets describe "$name" >/dev/null 2>&1; then
    ok "$name exists"
  else
    bad "$name is missing from Secret Manager"
    MISSING_SECRETS+=("$name")
  fi
done
if (( ${#MISSING_SECRETS[@]} )); then
  say ""
  say "Run the provisioning wizard's stage 6, which creates all five and binds each to the"
  say "production identity. It is idempotent and will keep the values that already exist."
  halt "${#MISSING_SECRETS[@]} secret(s) missing: ${MISSING_SECRETS[*]}"
fi

say ""
say "Existing is not the same claim as readable by the box. The VM runs as the production"
say "identity, so that is the identity the binding has to name."
for name in "${PRODUCTION_SECRETS[@]}"; do
  if gc secrets get-iam-policy "$name" \
       --flatten="bindings[].members" \
       --filter="bindings.role=roles/secretmanager.secretAccessor AND bindings.members:${VOX_PRODUCTION_SA}" \
       --format='value(bindings.members)' 2>/dev/null | grep -q .; then
    ok "$name is readable by the production identity"
  else
    bad "$name exists but is NOT bound to $VOX_PRODUCTION_SA"
  fi
done
if (( VERIFY_FAILURES > 0 )); then
  halt "a secret the container reads is not readable by the identity the container runs as"
fi

# excluded_from_context PATH — true when `.dockerignore` confidently keeps PATH out of the build
# context that `COPY . .` reads.
#
# **Conservative by construction.** It implements only the pattern forms this repo's
# `.dockerignore` actually uses — a bare name, `**/name`, `*.ext`, `**/*.ext`, `name.*`, and a
# directory prefix — and answers "not excluded" for everything it does not recognise. Docker's
# matcher is richer than this one. Being wrong in the permissive direction would turn stage 3's
# warning into a silent pass, which is the exact failure this block exists to undo; being wrong in
# the strict direction costs the operator one glance at a filename.
#
# It also gives up entirely on a negation line. `!pattern` re-includes what an earlier pattern
# excluded, and honouring the earlier pattern while ignoring the later one would report a file as
# absent from an image that contains it. There are no negations in the file today; if one appears,
# this reports every dirty path as reaching the image and the operator reads the names.
excluded_from_context() {
  local path="$1" pat base
  [ -f "$DOCKERIGNORE" ] || return 1
  grep -q '^[[:space:]]*!' "$DOCKERIGNORE" && return 1
  # `git status --porcelain --untracked-files=normal` collapses an untracked directory to a single
  # entry with a trailing slash. Without stripping it the basename is the empty string, so a
  # directory called `certs.pem/` would sail past a `*.pem` pattern — the containment branch below
  # happens to catch the common case, and the glob branch does not. Normalise once, here.
  path="${path%/}"
  [ -n "$path" ] || return 1
  base="${path##*/}"
  while IFS= read -r pat; do
    pat="${pat%$'\r'}"
    case "$pat" in ''|'#'*) continue ;; esac
    pat="${pat#./}"; pat="${pat%/}"
    # Strip a *literal* leading `**/` only. Unquoted, `${pat#**/}` is a glob that eats any leading
    # directory, which would turn `deploy/README.md` into `README.md` and exclude every README in
    # the tree.
    case "$pat" in '**/'*) pat="${pat#'**/'}" ;; esac
    [ -n "$pat" ] || continue
    # An exact path, or anything beneath it when the pattern names a directory.
    [ "$path" = "$pat" ] && return 0
    case "$path" in "$pat"/*) return 0 ;; esac
    # The same name at any depth, as a file or as a directory the path sits under.
    case "$path" in */"$pat"|*/"$pat"/*) return 0 ;; esac
    # A glob, read against the basename the way `**/*.ext` and `.env.*` are meant to be. The
    # unquoted `$pat` is the point rather than an oversight — quoting it, as SC2254 asks, would
    # match `*.pem` as the four literal characters and silently stop excluding every key file in
    # the tree. The branch is only reached for patterns that contain a `*`.
    # shellcheck disable=SC2254
    case "$pat" in *'*'*) case "$base" in $pat) return 0 ;; esac ;; esac
  done < "$DOCKERIGNORE"
  return 1
}

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The local image is present, and it is the one you think it is"
if ! dk image inspect "$LOCAL_IMAGE" >/dev/null 2>&1; then
  say "The image is not on this machine. Building it takes roughly ten minutes:"
  say ""
  note "  docker build -t $LOCAL_IMAGE ."
  note "  (the Dockerfile is at the repo root, not under deploy/)"
  say ""
  say "This wizard does not build it for you. A ten-minute build inside a stage that clears"
  say "the screen hides its own output, and a failed build should be read where it happened."
  halt "$LOCAL_IMAGE is not present locally"
fi
IMAGE_ID=$(dk image inspect "$LOCAL_IMAGE" --format '{{.Id}}')
IMAGE_CREATED=$(dk image inspect "$LOCAL_IMAGE" --format '{{.Created}}')
# `docker image inspect --format '{{.Size}}'` is NOT the figure to show here. Under Docker Desktop's
# containerd image store it reported 515 MB for an image `docker images` and `docker system df` both
# put at 2.06 GB — a four-fold understatement, in the two places where the number is the point: what
# the registry will be billed for, and how long stage 8 should expect to wait for the first pull. An
# operator told to expect 515 MB would read a normal 2 GB pull as a hung deploy.
IMAGE_SIZE=$(dk images "$LOCAL_IMAGE" --format '{{.Size}}' | head -n1)
ok "$LOCAL_IMAGE is present"
note "  id       ${IMAGE_ID:0:19}"
note "  built    $IMAGE_CREATED"
note "  size     $IMAGE_SIZE"
say ""
say "The registry tag records which commit produced this image, so a box running an old"
say "digest can be traced back to a tree rather than to a date."
GIT_SHA=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "nogit")
# This check used to be `git diff --quiet` over the whole tree behind one unqualified sentence, and
# running it found three faults:
#
#   1. `git diff` alone sees neither *staged* changes nor untracked files. Both land in the image
#      through `COPY . .`, and a staged-but-uncommitted change is precisely a tag that lies.
#   2. It named nothing, so an operator had to leave the wizard and go look — at the one prompt in
#      it that is asking them to think about something else.
#   3. It never asked whether the dirty files reach the image at all. A `.gitignore` edit that has
#      been deliberately uncommitted here for weeks made it fire on every single run, and a warning
#      that fires every time discriminates nothing. It spends the credibility of the judgement it
#      was protecting: the next firing, on a build that genuinely is misdescribed, reads as noise.
#
# So: name the files, and split them by whether the build context carries them. Only the first list
# is a warning. The second is printed anyway, because "this is dirty and it does not matter" is a
# thing the operator should be able to check rather than take on trust.
DIRTY_IN_IMAGE=""
DIRTY_OUT_OF_IMAGE=""
while IFS= read -r _dirty; do
  # `--porcelain` prefixes two status columns and a space; a rename arrives as `old -> new` and it
  # is the new path that is in the tree.
  _dirty="${_dirty:3}"
  case "$_dirty" in *' -> '*) _dirty="${_dirty##* -> }" ;; esac
  _dirty="${_dirty%\"}"; _dirty="${_dirty#\"}"
  [ -n "$_dirty" ] || continue
  if excluded_from_context "$_dirty"; then
    DIRTY_OUT_OF_IMAGE="${DIRTY_OUT_OF_IMAGE}${_dirty}"$'\n'
  else
    DIRTY_IN_IMAGE="${DIRTY_IN_IMAGE}${_dirty}"$'\n'
  fi
done < <(git -C "$REPO_ROOT" status --porcelain --untracked-files=normal 2>/dev/null)
if [ -n "$DIRTY_IN_IMAGE" ]; then
  warn "these are uncommitted and do reach the image, so tag $GIT_SHA does not fully describe this build:"
  while IFS= read -r _dirty; do [ -n "$_dirty" ] && note "    $_dirty"; done <<< "$DIRTY_IN_IMAGE"
fi
if [ -n "$DIRTY_OUT_OF_IMAGE" ]; then
  note "  uncommitted, but kept out of the image by .dockerignore, so the tag is unaffected:"
  while IFS= read -r _dirty; do [ -n "$_dirty" ] && note "    $_dirty"; done <<< "$DIRTY_OUT_OF_IMAGE"
fi
TAG="$GIT_SHA"
say ""
note "It will be pushed as $IMAGE_PATH:$TAG"
warn "If this image was not built from $GIT_SHA, stop and rebuild — the tag would be a lie."
confirm "Is $LOCAL_IMAGE the build you want deployed?" || halt "stopped at your request, before anything was pushed"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Push, and let the registry say what actually arrived"
say "This is the first stage that costs money and the first that leaves this machine."
say "$IMAGE_SIZE of registry storage, billed monthly, plus the transfer."
say ""
warn "The push is not reversible by re-running: a digest that exists in the registry exists."
confirm "Push $LOCAL_IMAGE to $IMAGE_PATH:$TAG?" || halt "stopped at your request, before anything was pushed"

say ""
say "Teaching docker to authenticate to this one registry host, and no others."
if gc auth configure-docker "${REGION}-docker.pkg.dev" --quiet >/dev/null 2>&1; then
  ok "docker is configured for ${REGION}-docker.pkg.dev"
else
  halt "gcloud auth configure-docker failed — is this account signed in? try: gcloud auth login"
fi

# Only the immutable tag is pushed. A `:latest` in a registry that a `Restart=always` unit pulls
# from is a foot-gun with a delay on it: the box would come back three weeks later running whatever
# `latest` had become, and nothing on the VM would record that it had changed.
dk tag "$LOCAL_IMAGE" "$IMAGE_PATH:$TAG"
say ""
say "Pushing. Layers already in the registry are skipped, so a re-push is fast."
if dk push "$IMAGE_PATH:$TAG"; then
  ok "push reported success"
else
  halt "the push failed — nothing on the VM has been touched, so it is safe to fix and re-run"
fi

say ""
say "What the local daemon believes it pushed and what the registry holds are two claims."
say "The digest that goes into the unit file is read back from the registry."
DIGEST=""
DIGEST=$(gc artifacts docker images describe "$IMAGE_PATH:$TAG" \
           --format='value(image_summary.digest)' 2>/dev/null || true)
if [[ "$DIGEST" != sha256:* ]]; then
  DIGEST=$(gc artifacts docker images list "$IMAGE_PATH" --include-tags \
             --filter="tags:$TAG" --format='value(version)' 2>/dev/null | head -n1 || true)
fi
if [[ "$DIGEST" != sha256:* ]]; then
  bad "could not read the digest back from the registry"
  say ""
  say "The push may well have worked; this is the read-back failing. What the registry lists:"
  gc artifacts docker images list "$IMAGE_PATH" --include-tags 2>&1 | sed 's/^/    /' || true
  say ""
  say "Find the digest for tag $TAG above and re-run with it pinned:"
  note "  VOX_IMAGE_DIGEST=sha256:... bash scripts/deploy-cloud-service.sh"
  # An `if` rather than `[[ ... ]] && assign` for legibility only. Worth knowing which way the
  # `set -e` hazard actually runs here, because it is the opposite of the usual assumption: bash
  # exempts a command that fails inside an `&&` list, so the short-circuit does *not* exit. The
  # trap is that a failing `cmd && ok "..."` passes silently instead — see the restart in stage 7.
  if [[ -n "${VOX_IMAGE_DIGEST:-}" ]]; then DIGEST="$VOX_IMAGE_DIGEST"; fi
fi
if [[ "$DIGEST" != sha256:* ]]; then
  halt "no digest to pin the unit file to"
fi
ok "the registry holds $DIGEST"
IMAGE_REF="${IMAGE_PATH}@${DIGEST}"
write_env VOX_IMAGE_REF "$IMAGE_REF"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The unit file is rendered against that digest"
say "deploy/cloud-init.yaml is a template, not a file to upload as it stands. Its ExecStart"
say "line ends in \${VOX_IMAGE}, and nothing in the repository defines that name."
say ""
warn "systemd expands an undefined \${VOX_IMAGE} to nothing, not to an error."
note "Uploaded unrendered, the unit would run 'docker run ... ' with no image argument, fail,"
note "and be restarted every ten seconds for ever by Restart=always. That is why this stage"
note "exists and why it refuses to hand on a file with anything unsubstituted left in it."

if [[ ! -f "$CLOUD_INIT" ]]; then halt "$CLOUD_INIT is missing"; fi
RENDERED=$(mktemp)
# The rendered file carries no secret — the whole point of the design is that it carries an image
# reference and nothing else — but it is still a temp file this wizard owns, and a `halt` two stages
# later should not leave it behind.
#
# This trap is the *only* cleanup. Five hand-written `rm -f "$RENDERED"` calls used to sit beside it
# on the paths someone happened to think of, which is belt-and-braces that rots: the sixth exit path
# forgets one, and nobody notices, because the trap quietly covers for it. One mechanism that always
# runs beats six that usually do.
trap 'rm -f "${RENDERED:-}"' EXIT
# A pinned digest rather than the tag: the tag is for humans reading the registry, the digest is
# what the machine must not be able to drift away from across a restart.
sed "s|\${VOX_IMAGE}|${IMAGE_REF}|g" "$CLOUD_INIT" > "$RENDERED"

if grep -q '\${' "$RENDERED"; then
  say ""
  say "Still unsubstituted after rendering:"
  grep -n '\${' "$RENDERED" | sed 's/^/    /'
  halt "the rendered unit file still contains a placeholder"
fi
ok "no placeholder survives rendering"

RENDERED_BYTES=$(wc -c < "$RENDERED" | tr -d ' ')
if (( RENDERED_BYTES > METADATA_MAX_BYTES )); then
  halt "the rendered file is $RENDERED_BYTES bytes, over the $METADATA_MAX_BYTES byte metadata limit"
fi
ok "$RENDERED_BYTES bytes, inside the $METADATA_MAX_BYTES byte limit for one metadata value"

say ""
say "The line the machine will actually run:"
grep -A5 'ExecStart=/usr/bin/docker run' "$RENDERED" | sed 's/^/    /'
say ""
confirm "Is that the image reference you expect?" || halt "stopped at your request, before the VM was touched"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The environment file, fetched by the box from Secret Manager"
say "The unit passes --env-file $SERVICE_ENV to docker run. cloud-init.yaml does not create"
say "that file, and docker refuses to start a container whose env-file is absent — which is"
say "the same ten-second crash loop as a missing image, from a different cause."
say ""
say "The box fetches its own values. It already runs as the production identity with the"
say "cloud-platform scope, and stage 2 has just checked that all five secrets are readable"
say "by exactly that identity, so nothing needs to pass through your terminal."
note "No value is typed, none is echoed, and none lands in a shell history — which is what"
note "ticket 03's last criterion asks for and what a pasted heredoc would have cost."
say ""
warn "It must never go into instance metadata: metadata is readable by anything on the box,"
note "and packages/production/src/proof/image-scan.ts exists to keep these values out of"
note "exactly that kind of place."

ENV_STATE=$(on_box_line "stat -c '%a %U:%G %s' $SERVICE_ENV 2>/dev/null || echo MISSING")

if [[ -z "$ENV_STATE" ]]; then
  halt "could not reach $INSTANCE over the IAP tunnel to check for $SERVICE_ENV"
fi

WRITE_ENV_FILE="no"
if [[ "$ENV_STATE" == "MISSING" ]]; then
  say ""
  say "$SERVICE_ENV does not exist on $INSTANCE yet."
  WRITE_ENV_FILE="yes"
else
  ok "$SERVICE_ENV already exists: $ENV_STATE"
  say ""
  say "Rewriting it picks up any secret whose value has been rotated since it was written."
  say "Leaving it alone is right if nothing has changed."
  if confirm "Rewrite $SERVICE_ENV from Secret Manager?"; then WRITE_ENV_FILE="yes"; fi
fi

if [[ "$WRITE_ENV_FILE" == "yes" ]]; then
  FETCHER="$REPO_ROOT/deploy/fetch-service-env.sh"
  [[ -f "$FETCHER" ]] || halt "$FETCHER is missing from the repository"
  say ""
  say "Copying deploy/fetch-service-env.sh to the box and running it under sudo. It asks the"
  say "metadata server for a token, reads the five secrets over the Secret Manager REST API,"
  say "and writes $SERVICE_ENV at mode 0600 — refusing to write anything at all if any one"
  say "of them cannot be read, because a partial env file starts a container with a silently"
  say "missing secret."
  note "Its output is names and byte counts. If you are looking for a value in it to check"
  note "one, it is not there, and that is the point."
  say ""

  if ! gc compute scp --tunnel-through-iap --zone="$ZONE" \
       "$FETCHER" "${INSTANCE}:~/fetch-service-env.sh" >/dev/null 2>&1; then
    halt "could not copy the fetcher to $INSTANCE over the tunnel"
  fi
  ok "copied to $INSTANCE"

  say ""
  # The script is removed whether it succeeded or not: it is not a secret, but a stray copy in a
  # home directory is one more thing on the box that nobody is maintaining.
  if on_box 'sudo bash ~/fetch-service-env.sh; status=$?; rm -f ~/fetch-service-env.sh; exit $status'; then
    ok "the box wrote $SERVICE_ENV from Secret Manager"
  else
    say ""
    note "The failure is printed above, by name. A 'request refused' means the secret exists"
    note "but is not readable by this instance's identity — which stage 2 checks, so a refusal"
    note "here after a clean stage 2 points at the instance's service account rather than at"
    note "the binding. Compare: gcloud compute instances describe $INSTANCE --zone=$ZONE"
    halt "the box could not write $SERVICE_ENV"
  fi

  ENV_STATE=$(on_box_line "stat -c '%a %U:%G %s' $SERVICE_ENV 2>/dev/null || echo MISSING")
  # Re-read from the box rather than trusting the exit status: the claim that matters before the
  # restart is that the file is there, not that a command which writes it returned zero.
  if [[ "$ENV_STATE" == "MISSING" ]]; then
    halt "the fetcher reported success but $SERVICE_ENV is not there"
  fi
fi

# Checked rather than assumed, and checked again after writing: the claim that matters is the state
# of the file on the box, not that a command which writes it exited zero.
ENV_MODE="${ENV_STATE%% *}"
ok "$SERVICE_ENV: $ENV_STATE"
if [[ "$ENV_MODE" != "600" && "$ENV_MODE" != "400" ]]; then
  bad "its mode is $ENV_MODE — every process on the box can read five production secrets"
  confirm "Continue with $SERVICE_ENV world-readable?" || halt "stopped at your request, before the VM was touched"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The metadata is applied, and the machine is restarted"
say "Everything the unit needs now exists: the image is in the registry, the secrets are"
say "bound, and $SERVICE_ENV is on the box. This is the point at which applying the"
say "metadata is safe, and it was not safe before."
say ""
say "cloud-init processes user-data during boot, so writing the metadata alone changes"
say "nothing on a running machine. The restart is what applies it."
warn "This stops and starts $INSTANCE. Anything running on it is interrupted."
note "A stop-then-start rather than a reset: a reset is a hard power cycle, and this box"
note "carries an ext4 disk that later deploys will find real Run data on."
confirm "Apply the metadata and restart $INSTANCE?" || halt "stopped at your request; the image is pushed but the VM is untouched"

if gc compute instances add-metadata "$INSTANCE" --zone="$ZONE" \
     --metadata-from-file="user-data=$RENDERED" >/dev/null; then
  ok "user-data applied to $INSTANCE"
else
  halt "add-metadata failed — the VM has not been restarted, so nothing has changed"
fi

say ""
say "Stopping."
if gc compute instances stop "$INSTANCE" --zone="$ZONE" >/dev/null; then
  ok "stopped"
else
  halt "the instance would not stop — the metadata is applied but has not taken effect"
fi
say "Starting."
if gc compute instances start "$INSTANCE" --zone="$ZONE" >/dev/null; then
  ok "started"
else
  halt "the instance would not start — it is stopped with the new metadata applied; start it by hand"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The unit came up, and it is running the digest that was pushed"
say "This is the stage that turns two documented intentions into observed facts: that"
say "Container-Optimized OS reads the user-data key and runs cloud-init over it, and that"
say "the mount unit's escaped name is the one systemd derives. Neither has ever been run."
say ""
say "First boot pulls $IMAGE_SIZE from Artifact Registry, so this is slow."
note "Polling for up to ten minutes. A pull, not a hang."

BOOT_OK="no"
for attempt in $(seq 1 40); do
  printf '  %s…%s attempt %s/40\r' "$DIM" "$RESET" "$attempt"
  STATE=$(on_box_line 'systemctl is-active vox-production.service 2>/dev/null || true')
  if [[ "$STATE" == "active" ]]; then BOOT_OK="yes"; break; fi
  sleep 15
done
printf '                                   \r'

if [[ "$BOOT_OK" != "yes" ]]; then
  bad "vox-production.service did not reach active within ten minutes"
  say ""
  say "What the box says. Read this rather than re-running:"
  on_box '
    echo "--- cloud-init ---";      sudo journalctl -u cloud-init --no-pager -n 25 2>/dev/null || echo none
    echo "--- mount unit ---";      systemctl status "mnt-disks-vox\x2druns.mount" --no-pager 2>&1 | head -15
    echo "--- service unit ---";    systemctl status vox-production.service --no-pager 2>&1 | head -25
  ' 2>/dev/null | sed 's/^/    /' || note "the tunnel did not answer"
  say ""
  note "A unit that is 'activating' is still pulling. A unit restarting every ten seconds is"
  note "the crash loop this wizard's ordering exists to prevent — read its ExecStart above."
  halt "the deployment did not come up"
fi
ok "vox-production.service is active"

say ""
say "Active is not the same claim as running the right image."
RUNNING=$(on_box_line 'docker inspect --format={{.Config.Image}} vox-production 2>/dev/null || true')
if [[ "$RUNNING" == "$IMAGE_REF" ]]; then
  ok "the running container is $DIGEST"
else
  bad "the box is running '$RUNNING', not the digest just pushed"
  note "Expected $IMAGE_REF"
fi

say ""
say "And that the disk is mounted, since the unit requires it and the service checks it."
on_box_line 'findmnt -no SOURCE,TARGET,FSTYPE /mnt/disks/vox-runs 2>/dev/null || echo "NOT MOUNTED"' \
  | sed 's/^/    /'

if (( VERIFY_FAILURES > 0 )); then
  SKIPPED+=("$VERIFY_FAILURES verification(s) failed — read them before claiming a conformance run")
fi

finish
printf '  %sWhat is deployed%s\n' "$BOLD" "$RESET"
note "  project    $VOX_CLOUD_PROJECT ($REGION / $ZONE)"
note "  image      $IMAGE_PATH:$TAG"
note "  digest     $DIGEST"
note "  instance   $INSTANCE, restarted with user-data applied"
printf '\n  %sWhat this has NOT shown%s\n' "$BOLD" "$RESET"
note "  that a render completes on the VM, with its egress observed"
note "  that the tunnel survives a three-minute synchronous render"
note "  that the mount survives a reboot, or that it is the intended disk rather than"
note "  merely a separate filesystem — ticket 04's identity.txt is what closes that"
printf '\n  %sThe tunnel%s\n' "$BOLD" "$RESET"
note "  gcloud compute ssh $INSTANCE --zone=$ZONE --tunnel-through-iap"
printf '\n'
