#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13

# Values this wizard captures live outside the repository, deliberately: ticket 03's last
# criterion is that no credential appears in the repository, a transcript or a shell history.
# Only non-secret configuration is written here. Every secret goes straight into Secret Manager
# from a hidden prompt and is never echoed, never written to a file and never passed as an argv
# element that `ps` or a shell history could show.
ENV_FILE="${VOX_CLOUD_ENV_FILE:-$HOME/.vox-cloud.env}"

# The topology, decided and recorded rather than chosen here. See `.scratch/cloud-phase/map.md`.
REGION="europe-west1"
ZONE="europe-west1-b"
MACHINE_TYPE="e2-standard-2"   # measured by ticket 11: 2.08 GB peak, 178 s under a two-vCPU cap
INSTANCE="vox-service"
DISK="vox-runs"
DISK_SIZE="50GB"
REPO="vox"
NETWORK="default"
NETWORK_TAG="vox-service"
ROUTER="vox-router"
NAT="vox-nat"
IAP_RANGE="35.235.240.0/20"    # the only range Google's IAP TCP forwarding connects from

# The four production secret names are fixed by the code and reused verbatim, per ticket 03's
# Further Notes. `service-host.ts` reads each through `required()` and will keep doing so; what
# changes is who populates the environment.
PRODUCTION_SECRETS=(ELEVENLABS_API_KEY VOX_GRANT_KEY VOX_RUN_HMAC_KEY VOX_RUN_KEY_ID)
CREW_SECRET="VOX_CREW_MODEL_KEY"

# ── gcloud, resolved once ─────────────────────────────────────────────────
# Git Bash on Windows finds the SDK's bash wrapper on some installs and only `gcloud.cmd` on
# others, and a wizard that dies on `command -v gcloud` after the operator has just installed it
# is the worst possible moment to be wrong about this.
GCLOUD=""
resolve_gcloud() {
  local candidate
  for candidate in gcloud gcloud.cmd; do
    if command -v "$candidate" >/dev/null 2>&1; then GCLOUD="$candidate"; return 0; fi
  done
  return 1
}
gc() { "$GCLOUD" "$@"; }

# ok/bad report a verification's outcome. Every stage ends in one of these, because an operator
# who followed thirteen steps and mistyped one should learn it at that step, not at ticket 07's
# first deploy.
VERIFY_FAILURES=0
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; VERIFY_FAILURES=$((VERIFY_FAILURES + 1)); }

# capture_secret NAME "prompt" reads a secret into the global $SECRET_VALUE, offering to generate
# one where a generated value is better than a typed one. Nothing is returned through a file.
SECRET_VALUE=""
capture_secret() {
  local name="$1" prompt="$2" generatable="${3:-no}" value="" exists="no"
  # A re-run must not make the operator retype secrets it already holds, and must never store an
  # empty version because they pressed Enter expecting it to keep what is there.
  if gc secrets describe "$name" >/dev/null 2>&1; then exists="yes"; fi
  if [[ "$exists" == "yes" ]]; then
    note "$name is already in Secret Manager. Press Enter to keep the value it has."
  elif [[ "$generatable" == "generate" ]]; then
    note "Press Enter on an empty prompt and the wizard generates 32 random bytes for you."
  fi
  ask_secret _CAPTURED "$prompt"
  value="${_CAPTURED:-}"
  if [[ -z "$value" && "$exists" == "no" && "$generatable" == "generate" ]]; then
    if command -v openssl >/dev/null 2>&1; then
      value=$(openssl rand -hex 32)
      ok "generated a 32-byte value for $name"
    else
      value=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
      ok "generated a 32-byte value for $name"
    fi
  fi
  SECRET_VALUE="$value"
}

# store_secret NAME grants exactly one identity access to the value in $SECRET_VALUE.
# The value reaches gcloud on stdin, never on the command line.
store_secret() {
  local name="$1" accessor="$2"
  if [[ -z "$SECRET_VALUE" ]]; then
    if gc secrets describe "$name" >/dev/null 2>&1; then
      gc secrets add-iam-policy-binding "$name" \
        --member="serviceAccount:$accessor" \
        --role=roles/secretmanager.secretAccessor >/dev/null
      ok "$name kept as it is, readable by $accessor"
    else
      bad "$name was left empty and does not exist yet — re-run and give it a value"
    fi
    return 0
  fi
  if gc secrets describe "$name" >/dev/null 2>&1; then
    note "$name already exists; adding a new version"
  else
    gc secrets create "$name" \
      --replication-policy=user-managed --locations="$REGION" >/dev/null
  fi
  printf '%s' "$SECRET_VALUE" | gc secrets versions add "$name" --data-file=- >/dev/null
  gc secrets add-iam-policy-binding "$name" \
    --member="serviceAccount:$accessor" \
    --role=roles/secretmanager.secretAccessor >/dev/null
  SECRET_VALUE=""
  ok "$name stored in $REGION, readable by $accessor"
}

banner "Vox production project — provisioning a trust boundary"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "The Google Cloud CLI is installed, and you are signed in"
if resolve_gcloud; then
  ok "found $GCLOUD"
else
  say "gcloud is not on this machine yet. It is the wizard's only prerequisite."
  open_url "https://cloud.google.com/sdk/docs/install"
  step "Download the Windows installer (GoogleCloudSDKInstaller.exe) and run it."
  step "Leave 'Bundled Python' ticked, and let it add gcloud to your PATH."
  step "When it offers to run 'gcloud init' at the end, decline — this wizard does that part."
  warn "Close this terminal and open a new one afterwards, or the new PATH will not be visible."
  pause "Press Enter once the installer has finished and you have re-opened the terminal."
  if ! resolve_gcloud; then
    bad "still cannot find gcloud on PATH — re-open the terminal and re-run this wizard"
    exit 1
  fi
  ok "found $GCLOUD"
fi

if gc auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then
  ok "already signed in as $(gc auth list --filter=status:ACTIVE --format='value(account)' | head -n1 || true)"
else
  say "A browser window will open for you to sign in."
  gc auth login
fi
OPERATOR=$(gc auth list --filter=status:ACTIVE --format='value(account)' | head -n1 || true)
if [[ -z "$OPERATOR" ]]; then bad "no active account after sign-in"; exit 1; fi
ok "signed in as $OPERATOR"
write_env VOX_CLOUD_OPERATOR "$OPERATOR"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The project exists, and its owner is named"
say "The production service holds live ElevenLabs credentials and signs Run ledgers, so its"
say "project is a trust boundary rather than a convenience. It gets its own project."
note "Project IDs are globally unique, lowercase, 6-30 characters, e.g. vox-studio-prod-7f3a"
ask VOX_CLOUD_PROJECT "Project ID to create or use:"
if [[ -z "${VOX_CLOUD_PROJECT:-}" ]]; then bad "a project ID is required"; exit 1; fi

if gc projects describe "$VOX_CLOUD_PROJECT" >/dev/null 2>&1; then
  ok "project $VOX_CLOUD_PROJECT already exists"
else
  say "Creating $VOX_CLOUD_PROJECT."
  gc projects create "$VOX_CLOUD_PROJECT" --name="Vox production"
fi
gc config set project "$VOX_CLOUD_PROJECT" >/dev/null
write_env VOX_CLOUD_PROJECT "$VOX_CLOUD_PROJECT"
write_env VOX_CLOUD_REGION "$REGION"
write_env VOX_CLOUD_ZONE "$ZONE"

if gc projects get-iam-policy "$VOX_CLOUD_PROJECT" \
     --flatten='bindings[].members' --filter='bindings.role:roles/owner' \
     --format='value(bindings.members)' 2>/dev/null | grep -q .; then
  ok "owner recorded: $(gc projects get-iam-policy "$VOX_CLOUD_PROJECT" --flatten='bindings[].members' --filter='bindings.role:roles/owner' --format='value(bindings.members)' | tr '\n' ' ' || true)"
else
  bad "the project has no owner binding — that is the one thing this stage exists to establish"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Billing is attached, and a budget alert is set"
say "A render is minutes of CPU with a headless browser attached, and this phase will run"
say "several by accident. The alert is the difference between noticing on the day and"
say "noticing on the invoice."
say ""
say "Your billing accounts:"
gc billing accounts list --format='table(name,displayName,open)' || true
note "Only an account with OPEN=True can be linked. A closed one cannot be used."
ask VOX_BILLING_ACCOUNT "Billing account ID (the XXXXXX-XXXXXX-XXXXXX part):"
if [[ -n "${VOX_BILLING_ACCOUNT:-}" ]]; then
  write_env VOX_BILLING_ACCOUNT "$VOX_BILLING_ACCOUNT"
  # Not fatal: the common failure here is a quota, and it has a specific remedy the operator
  # can act on. Killing the wizard at stage 3 of 13 teaches them nothing they can use.
  if LINK_ERROR=$(gc billing projects link "$VOX_CLOUD_PROJECT" \
       --billing-account="$VOX_BILLING_ACCOUNT" 2>&1 >/dev/null); then
    ok "linked $VOX_CLOUD_PROJECT to $VOX_BILLING_ACCOUNT"
  else
    bad "could not link the project to $VOX_BILLING_ACCOUNT"
    printf '%s\n' "$LINK_ERROR" | sed 's/^/    /'
    if grep -q 'quota' <<<"$LINK_ERROR"; then
      say ""
      warn "That is the projects-per-billing-account cap, not a problem with your project."
      say "Google allows five linked projects per billing account unless the quota is raised."
      say "These are the projects currently holding the slots:"
      gc billing projects list --billing-account="$VOX_BILLING_ACCOUNT" \
        --format='table(projectId,billingEnabled)' 2>/dev/null | sed 's/^/    /' || true
      say ""
      say "Free one slot, then re-run this wizard:"
      note "  gcloud billing projects unlink PROJECT_ID"
      warn "Unlinking disables every paid service on that project. Pick one you are done with."
      note "Or request a raise, which takes days: https://support.google.com/code/contact/billing_quota_increase"
    fi
    SKIPPED+=("billing not linked to $VOX_CLOUD_PROJECT")
    say ""
    confirm "Stop here and fix billing? (recommended — nothing after this stage will work)" && exit 1
  fi
fi

if [[ "$(gc billing projects describe "$VOX_CLOUD_PROJECT" --format='value(billingEnabled)' 2>/dev/null)" == "True" ]]; then
  ok "billing is enabled on $VOX_CLOUD_PROJECT"
else
  bad "billing is not enabled — every stage after this one will fail"
fi

gc services enable billingbudgets.googleapis.com >/dev/null 2>&1 || true
ask VOX_BUDGET_AMOUNT "Monthly budget in your billing currency [50]:"
VOX_BUDGET_AMOUNT="${VOX_BUDGET_AMOUNT:-50}"
if gc billing budgets list --billing-account="$VOX_BILLING_ACCOUNT" \
     --format='value(displayName)' 2>/dev/null | grep -q '^vox-production$'; then
  ok "budget 'vox-production' already exists"
else
  if gc billing budgets create \
       --billing-account="$VOX_BILLING_ACCOUNT" \
       --display-name="vox-production" \
       --filter-projects="projects/$VOX_CLOUD_PROJECT" \
       --budget-amount="${VOX_BUDGET_AMOUNT}" \
       --threshold-rule=percent=0.5 \
       --threshold-rule=percent=0.9 \
       --threshold-rule=percent=1.0 >/dev/null 2>&1; then
    ok "budget set at ${VOX_BUDGET_AMOUNT}/month with alerts at 50%, 90% and 100%"
  else
    warn "could not create the budget from the CLI; the console is one click"
    open_url "https://console.cloud.google.com/billing/$VOX_BILLING_ACCOUNT/budgets"
    step "Create a budget scoped to project $VOX_CLOUD_PROJECT at ${VOX_BUDGET_AMOUNT}/month."
    SKIPPED+=("budget alert for $VOX_CLOUD_PROJECT")
    pause "Press Enter when the budget exists."
  fi
fi
write_env VOX_BUDGET_AMOUNT "$VOX_BUDGET_AMOUNT"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The APIs this topology needs are enabled"
say "Six services, and no more than six. Each one is a surface, and a surface nobody"
say "uses is a surface nobody is watching."
for api in compute.googleapis.com artifactregistry.googleapis.com \
           secretmanager.googleapis.com iap.googleapis.com \
           iamcredentials.googleapis.com billingbudgets.googleapis.com; do
  printf '  %s…%s enabling %s\n' "$DIM" "$RESET" "$api"
  gc services enable "$api" >/dev/null
done
ENABLED=$(gc services list --enabled --format='value(config.name)')
for api in compute.googleapis.com artifactregistry.googleapis.com \
           secretmanager.googleapis.com iap.googleapis.com; do
  if grep -q "^${api}$" <<<"$ENABLED"; then ok "$api"; else bad "$api is not enabled"; fi
done

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Two service identities, not one"
say "Locally the crew reaches production through a launcher and never holds a production"
say "secret. One identity for both sides would make that sentence false by construction,"
say "and it would become false silently. Additional service accounts are free."
for pair in "vox-production:The production service" "vox-crew:The local crew"; do
  sa="${pair%%:*}"; label="${pair#*:}"
  if gc iam service-accounts describe "${sa}@${VOX_CLOUD_PROJECT}.iam.gserviceaccount.com" >/dev/null 2>&1; then
    ok "$sa already exists"
  else
    gc iam service-accounts create "$sa" --display-name="$label" >/dev/null
    ok "created $sa"
  fi
done
VOX_PRODUCTION_SA="vox-production@${VOX_CLOUD_PROJECT}.iam.gserviceaccount.com"
VOX_CREW_SA="vox-crew@${VOX_CLOUD_PROJECT}.iam.gserviceaccount.com"
write_env VOX_PRODUCTION_SA "$VOX_PRODUCTION_SA"
write_env VOX_CREW_SA "$VOX_CREW_SA"

say ""
say "Stage 8 proves these two cannot read each other's secrets, which needs you to be able"
say "to borrow each identity for one command."
for sa in "$VOX_PRODUCTION_SA" "$VOX_CREW_SA"; do
  gc iam service-accounts add-iam-policy-binding "$sa" \
    --member="user:$OPERATOR" --role=roles/iam.serviceAccountTokenCreator >/dev/null
done
ok "you can impersonate both identities for the proof in stage 8"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The four production secrets, readable by production alone"
say "These names are fixed by the code and are reused verbatim. Input is hidden, and no"
say "value is written to disk or passed on a command line."
capture_secret ELEVENLABS_API_KEY "ELEVENLABS_API_KEY:"
store_secret ELEVENLABS_API_KEY "$VOX_PRODUCTION_SA"
capture_secret VOX_GRANT_KEY "VOX_GRANT_KEY:" generate
store_secret VOX_GRANT_KEY "$VOX_PRODUCTION_SA"
capture_secret VOX_RUN_HMAC_KEY "VOX_RUN_HMAC_KEY:" generate
store_secret VOX_RUN_HMAC_KEY "$VOX_PRODUCTION_SA"
capture_secret VOX_RUN_KEY_ID "VOX_RUN_KEY_ID (an identifier, e.g. vox-cloud-key-v1):"
store_secret VOX_RUN_KEY_ID "$VOX_PRODUCTION_SA"

for name in "${PRODUCTION_SECRETS[@]}"; do
  if gc secrets describe "$name" >/dev/null 2>&1; then ok "$name exists"; else bad "$name is missing"; fi
done

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The crew's model credential, readable by the crew alone"
say "The crew holds a model credential and the VOX_IPC_TOKEN capability. Neither is a"
say "production secret, and production must not be able to read either."
capture_secret "$CREW_SECRET" "The crew's model API key:"
store_secret "$CREW_SECRET" "$VOX_CREW_SA"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The separation is proved, by two commands expected to fail"
say "This is the ticket's actual deliverable. That the project exists is not the claim;"
say "that it keeps the two sides apart is the claim. A run that shows either command"
say "succeeding is the finding, and it is worth more than a run where both fail."
say ""
PROOF_FAILURES=0

printf '  %s…%s crew identity reading a production secret (must fail)\n' "$DIM" "$RESET"
if gc secrets versions access latest --secret=ELEVENLABS_API_KEY \
     --impersonate-service-account="$VOX_CREW_SA" >/dev/null 2>&1; then
  bad "THE CREW IDENTITY READ ELEVENLABS_API_KEY — decision 8 does not hold in this project"
  PROOF_FAILURES=$((PROOF_FAILURES + 1))
else
  ok "refused: the crew identity cannot read ELEVENLABS_API_KEY"
fi

printf '  %s…%s production identity reading the crew secret (must fail)\n' "$DIM" "$RESET"
if gc secrets versions access latest --secret="$CREW_SECRET" \
     --impersonate-service-account="$VOX_PRODUCTION_SA" >/dev/null 2>&1; then
  bad "THE PRODUCTION IDENTITY READ $CREW_SECRET — decision 8 does not hold in this project"
  PROOF_FAILURES=$((PROOF_FAILURES + 1))
else
  ok "refused: the production identity cannot read $CREW_SECRET"
fi

printf '  %s…%s production identity reading its own secret (must succeed)\n' "$DIM" "$RESET"
if gc secrets versions access latest --secret=ELEVENLABS_API_KEY \
     --impersonate-service-account="$VOX_PRODUCTION_SA" >/dev/null 2>&1; then
  ok "granted: the production identity can read its own secret"
else
  bad "the production identity cannot read its own secret — the grant did not take"
  PROOF_FAILURES=$((PROOF_FAILURES + 1))
fi
note "The third check is here because two refusals also happen when nothing works at all."

if (( PROOF_FAILURES > 0 )); then
  warn "the separation is not proved; stop here and fix it before deploying anything"
  confirm "Continue anyway?" || exit 1
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Artifact Registry, in the one region"
if gc artifacts repositories describe "$REPO" --location="$REGION" >/dev/null 2>&1; then
  ok "repository $REPO already exists in $REGION"
else
  gc artifacts repositories create "$REPO" \
    --repository-format=docker --location="$REGION" \
    --description="Vox production service images" >/dev/null
  ok "created $REPO in $REGION"
fi
gc artifacts repositories add-iam-policy-binding "$REPO" --location="$REGION" \
  --member="serviceAccount:$VOX_PRODUCTION_SA" \
  --role=roles/artifactregistry.reader >/dev/null
ok "the production identity can pull, and nothing else has been granted push"
write_env VOX_CLOUD_REPO "${REGION}-docker.pkg.dev/${VOX_CLOUD_PROJECT}/${REPO}"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "The network: nothing in, and a metered way out"
say "Ingress is closed before anything is deployed behind it. A service that is reachable"
say "while being configured has been reachable, and that window does not close retroactively."
say ""
say "Outbound needs saying out loud: a VM with no external address cannot reach the"
say "internet at all without Cloud NAT, and the synthesizer and the font host are both"
say "outside Google. NAT is what makes 'no external address' survivable."

if gc compute firewall-rules describe vox-deny-all-ingress >/dev/null 2>&1; then
  ok "vox-deny-all-ingress already exists"
else
  gc compute firewall-rules create vox-deny-all-ingress \
    --network="$NETWORK" --direction=INGRESS --action=DENY --rules=all \
    --source-ranges=0.0.0.0/0 --priority=65000 \
    --description="Closes the default network's permissive rules. Priority beats 65534." >/dev/null
  ok "created vox-deny-all-ingress at priority 65000"
fi

if gc compute firewall-rules describe vox-allow-iap-ssh >/dev/null 2>&1; then
  ok "vox-allow-iap-ssh already exists"
else
  gc compute firewall-rules create vox-allow-iap-ssh \
    --network="$NETWORK" --direction=INGRESS --action=ALLOW --rules=tcp:22 \
    --source-ranges="$IAP_RANGE" --target-tags="$NETWORK_TAG" --priority=1000 \
    --description="The only ingress: Google's IAP TCP forwarding range, SSH, tagged hosts." >/dev/null
  ok "created vox-allow-iap-ssh from $IAP_RANGE only"
fi

if gc compute routers describe "$ROUTER" --region="$REGION" >/dev/null 2>&1; then
  ok "router $ROUTER already exists"
else
  gc compute routers create "$ROUTER" --network="$NETWORK" --region="$REGION" >/dev/null
  ok "created router $ROUTER"
fi
if gc compute routers nats describe "$NAT" --router="$ROUTER" --region="$REGION" >/dev/null 2>&1; then
  ok "NAT $NAT already exists"
else
  gc compute routers nats create "$NAT" --router="$ROUTER" --region="$REGION" \
    --auto-allocate-nat-external-ips --nat-all-subnet-ip-ranges >/dev/null
  ok "created NAT $NAT — outbound only, no inbound path is created by this"
fi

gc projects add-iam-policy-binding "$VOX_CLOUD_PROJECT" \
  --member="user:$OPERATOR" --role=roles/iap.tunnelResourceAccessor >/dev/null 2>&1 || true
ok "you may open an IAP tunnel to this project"
warn "Egress cannot be restricted by hostname here: VPC firewall rules take CIDR ranges only,"
note "and both the synthesizer and the font host sit behind CDNs. See ticket 07."

# ── 11 ────────────────────────────────────────────────────────────────────
stage "The persistent disk the run store needs"
say "RunStore uses hardlinks, atomic rename and lock files. That is a real filesystem or"
say "it is the wrong storage, and ticket 04 proves it on this disk before anything trusts it."
# The region is a decision; the zone inside it is not. A zone can be out of capacity for a disk
# type at any moment, which is a Google-side shortage rather than anything wrong here, so try the
# region's zones in turn and record whichever one supplies it. Stages 12 and 13 follow this zone.
ZONE_CANDIDATES=("$ZONE" "${REGION}-c" "${REGION}-d")
DISK_ZONE=""
for candidate in "${ZONE_CANDIDATES[@]}"; do
  if gc compute disks describe "$DISK" --zone="$candidate" >/dev/null 2>&1; then
    DISK_ZONE="$candidate"
    ok "disk $DISK already exists in $candidate"
    break
  fi
done
if [[ -z "$DISK_ZONE" ]]; then
  for candidate in "${ZONE_CANDIDATES[@]}"; do
    printf '  %s…%s asking %s for a %s %s disk\n' "$DIM" "$RESET" "$candidate" "$DISK_SIZE" "pd-balanced"
    if DISK_ERROR=$(gc compute disks create "$DISK" \
         --size="$DISK_SIZE" --type=pd-balanced --zone="$candidate" 2>&1 >/dev/null); then
      DISK_ZONE="$candidate"
      ok "created $DISK ($DISK_SIZE, pd-balanced) in $candidate"
      break
    fi
    if grep -q 'ZONE_RESOURCE_POOL_EXHAUSTED' <<<"$DISK_ERROR"; then
      warn "$candidate has no capacity for this disk right now; trying the next zone"
    else
      bad "could not create the disk in $candidate"
      printf '%s\n' "$DISK_ERROR" | sed 's/^/    /'
      break
    fi
  done
fi
if [[ -z "$DISK_ZONE" ]]; then
  bad "no zone in $REGION could supply the disk — try again later, or lower DISK_SIZE"
  note "The region is a recorded decision and is not the thing to change here."
  exit 1
fi
ZONE="$DISK_ZONE"
write_env VOX_CLOUD_ZONE "$ZONE"
write_env VOX_CLOUD_DISK "$DISK"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "The VM, with no external address"
say "Container-Optimized OS, $MACHINE_TYPE — the machine type ticket 11 measured rather"
say "than guessed. The container itself is ticket 07's; this stage creates the box."
if gc compute instances describe "$INSTANCE" --zone="$ZONE" >/dev/null 2>&1; then
  ok "instance $INSTANCE already exists"
else
  gc compute instances create "$INSTANCE" \
    --zone="$ZONE" --machine-type="$MACHINE_TYPE" \
    --image-family=cos-stable --image-project=cos-cloud \
    --no-address \
    --service-account="$VOX_PRODUCTION_SA" --scopes=cloud-platform \
    --disk="name=${DISK},device-name=${DISK},mode=rw,auto-delete=no" \
    --tags="$NETWORK_TAG" \
    --shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring >/dev/null
  ok "created $INSTANCE with no external address"
fi
write_env VOX_CLOUD_INSTANCE "$INSTANCE"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Ingress is refused from outside, and the tunnel works"
say "Two things, and they are different claims: that there is no public address, and that"
say "the one route in still reaches the box."

ACCESS_CONFIGS=$(gc compute instances describe "$INSTANCE" --zone="$ZONE" \
  --format='value(networkInterfaces[0].accessConfigs[0].natIP)' 2>/dev/null || true)
if [[ -z "$ACCESS_CONFIGS" ]]; then
  ok "no external IP: there is no address for an unauthenticated request to arrive at"
else
  bad "the instance has external IP $ACCESS_CONFIGS — ingress is not closed"
fi

INGRESS_ALLOWS=$(gc compute firewall-rules list \
  --filter="network=$NETWORK AND direction=INGRESS AND disabled=false" \
  --format='value(name,sourceRanges.list(),allowed[].map().firewall_rule().list())' 2>/dev/null || true)
say ""
say "Ingress rules now in force:"
printf '%s\n' "$INGRESS_ALLOWS" | sed 's/^/    /'
note "Anything here whose source is not $IAP_RANGE is a rule to explain or delete."

say ""
say "Now the tunnel. This opens an SSH connection through IAP and runs one command."
note "The first run generates an SSH key and may ask for a passphrase."
if gc compute ssh "$INSTANCE" --zone="$ZONE" --tunnel-through-iap \
     --command='echo tunnel-ok' 2>/dev/null | grep -q tunnel-ok; then
  ok "the IAP tunnel reaches the instance"
else
  bad "the IAP tunnel did not reach the instance"
  note "Common causes: the instance is still booting, or roles/iap.tunnelResourceAccessor"
  note "has not propagated yet. Wait a minute and re-run this wizard; it is idempotent."
fi

if (( VERIFY_FAILURES > 0 )); then
  SKIPPED+=("$VERIFY_FAILURES verification(s) failed — re-read the stages above before ticket 07")
fi

finish
printf '  %sWhat exists now%s\n' "$BOLD" "$RESET"
note "  project      $VOX_CLOUD_PROJECT ($REGION / $ZONE)"
note "  identities   $VOX_PRODUCTION_SA"
note "               $VOX_CREW_SA"
note "  secrets      ${PRODUCTION_SECRETS[*]} → production only"
note "               $CREW_SECRET → crew only"
note "  registry     ${REGION}-docker.pkg.dev/${VOX_CLOUD_PROJECT}/${REPO}"
note "  disk         $DISK ($DISK_SIZE) in $ZONE"
note "  instance     $INSTANCE, no external address, reachable only through IAP"
printf '\n  %sNext%s\n' "$BOLD" "$RESET"
note "  ticket 04 — prove POSIX semantics on $DISK before the run store trusts it"
note "  ticket 07 — build and push the image, and mount the disk into the container"
note "  the tunnel — gc compute ssh $INSTANCE --zone=$ZONE --tunnel-through-iap"
printf '\n'
